variable "aws-region"  {}
variable "vpc1-name"  {}
variable "vpc1-cidr"  {}
variable "main-cidr"  {}
variable "vpc1-type" {}
variable "public-subnet-a"  {}
variable "public-subnet-b"  {}
variable "private-subnet-a"  {}
variable "private-subnet-b"  {}
variable "mgmt-subnet-a"  {}
variable "mgmt-subnet-b"  {}
variable "tgw-subnet-a"  {}
variable "tgw-subnet-b"  {}
variable "public-cidr-a"  {}
variable "public-cidr-b"  {}
variable "private-cidr-a"  {}
variable "private-cidr-b"  {}
variable "mgmt-cidr-a"  {}
variable "mgmt-cidr-b"  {}
variable "tgw-cidr-a"  {}
variable "tgw-cidr-b"  {}
variable "igw-name"  {}
variable "tgw-name"  {}
variable "tgw-rt1-name" {}
variable "tgw-rt1-type" {}
variable "tgw-rt2-name" {}
variable "tgw-rt2-type" {}
variable "rt1-postfix"  {}
variable "rt2-postfix"  {}
variable "rt3-postfix"  {}
variable "rt4-postfix"  {}
variable "rt5-postfix"  {}
variable "on-prem-cidr" {}
variable "ssh-key-name"  {}
variable "ssh-key" {}
variable "asav-instance-size" {}
variable "asa-ami-id" {}
variable "asa-instances" {}
variable "asa-license-throughput" {}
variable "ami-owner" {}
variable "ec2-instance-size" {}
variable "instance-ami-id" {}
variable "instance01-name" {}
variable "instance01-az" {}
variable "instance01-tg-attach" {}
variable "instance01-public-ip" {}
variable "instance01-from-to-port" {}
variable "instance01-proto" {}
variable "instance02-name" {}
variable "instance02-az" {}
variable "instance02-tg-attach" {}
variable "instance02-public-ip" {}
variable "instance02-from-to-port" {}
variable "instance02-proto" {}
variable "instance03-name" {}
variable "instance03-az" {}
variable "instance03-tg-attach" {}
variable "instance03-public-ip" {}
variable "instance03-from-to-port" {}
variable "instance03-proto" {}
variable "instance04-name" {}
variable "instance04-az" {}
variable "instance04-tg-attach" {}
variable "instance04-public-ip" {}
variable "instance04-from-to-port" {}
variable "instance04-proto" {}
